/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pythonprogramtester;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Willhoft
 */
public class SettingsDialog extends javax.swing.JDialog {

    /**
     * Creates new form SettingsDialog
     */
    public SettingsDialog(java.awt.Frame parent, boolean modal, ProgramSettings set) {
        super(parent, modal);
        settings = set;

        initComponents();

        pythonExecutableField.setText(settings.getPythonExecutable());
        lastTestCaseField.setText(settings.getLastTestCase());
        lastTestingPathField.setText(settings.getLastTestingPath());
        tempProgramFileField.setText(settings.getTempProgramFileName());
        tempInputFileField.setText(settings.getTempInputFileName());
        tempOutputFileField.setText(settings.getTempOutputFileName());
        resultsFileNameField.setText(settings.getResultsFileName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        pythonExecutableLabel = new javax.swing.JLabel();
        lastTestCaseLabel = new javax.swing.JLabel();
        lastTestingPathLabel = new javax.swing.JLabel();
        programFileNameLabel = new javax.swing.JLabel();
        tempInputFileLabel = new javax.swing.JLabel();
        tempOutputFileLabel = new javax.swing.JLabel();
        resultsFileNameLabel = new javax.swing.JLabel();
        tempProgramFileField = new javax.swing.JTextField();
        tempInputFileField = new javax.swing.JTextField();
        tempOutputFileField = new javax.swing.JTextField();
        resultsFileNameField = new javax.swing.JTextField();
        pythonExecutableField = new javax.swing.JTextField();
        lastTestCaseField = new javax.swing.JTextField();
        lastTestingPathField = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        idleExecutableLabel = new javax.swing.JLabel();
        idleExecutableField = new javax.swing.JTextField();
        pythonTestButton = new javax.swing.JButton();
        idleTestButton = new javax.swing.JButton();
        infoOnlyLabel = new javax.swing.JLabel();
        winDefaultsButton = new javax.swing.JButton();
        macDefaultsButton = new javax.swing.JButton();
        linuxDefaultsButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Python Program Tester - Settings");

        TitleLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        TitleLabel.setText("Set Values based on your OS Environment:");

        pythonExecutableLabel.setText("Python Executable:");

        lastTestCaseLabel.setText("Last Test Case:");

        lastTestingPathLabel.setText("Last Testing Path:");

        programFileNameLabel.setText("Temporary Program File Name:");

        tempInputFileLabel.setText("Temporary Input File Name:");

        tempOutputFileLabel.setText("Temporary Output File Name:");

        resultsFileNameLabel.setText("Results File Name:");

        lastTestCaseField.setEnabled(false);

        lastTestingPathField.setEnabled(false);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        idleExecutableLabel.setText("IDLE Executable:");

        pythonTestButton.setText("Test");
        pythonTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonTestButtonActionPerformed(evt);
            }
        });

        idleTestButton.setText("Test");

        infoOnlyLabel.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        infoOnlyLabel.setText("Information only:");

        winDefaultsButton.setText("Set Windows Defaults");
        winDefaultsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        macDefaultsButton.setText("Set MacOS Defaults");
        macDefaultsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        macDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macDefaultsButtonActionPerformed(evt);
            }
        });

        linuxDefaultsButton.setText("Set Linux Defaults");
        linuxDefaultsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        linuxDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linuxDefaultsButtonActionPerformed(evt);
            }
        });

        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Please make any necessary changes ...");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastTestCaseLabel)
                            .addComponent(lastTestingPathLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastTestingPathField)
                            .addComponent(lastTestCaseField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idleExecutableLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idleExecutableField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pythonExecutableLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pythonExecutableField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pythonTestButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idleTestButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(programFileNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempProgramFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(winDefaultsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tempOutputFileLabel)
                            .addComponent(tempInputFileLabel)
                            .addComponent(resultsFileNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tempOutputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tempInputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(macDefaultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(linuxDefaultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 226, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultsFileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SaveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelButton))))
                    .addComponent(infoOnlyLabel)
                    .addComponent(TitleLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGap(16, 16, 16)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pythonExecutableLabel)
                    .addComponent(pythonExecutableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(pythonTestButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idleExecutableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idleTestButton)
                        .addComponent(jButton2))
                    .addComponent(idleExecutableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempProgramFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(winDefaultsButton)
                    .addComponent(programFileNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempInputFileLabel)
                    .addComponent(tempInputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macDefaultsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempOutputFileLabel)
                    .addComponent(tempOutputFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linuxDefaultsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultsFileNameLabel)
                    .addComponent(resultsFileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton)
                    .addComponent(SaveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoOnlyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastTestCaseLabel)
                    .addComponent(lastTestCaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastTestingPathLabel)
                    .addComponent(lastTestingPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        settings.setPythonExecutable(pythonExecutableField.getText().replace("\\", "/"));
        settings.setLastTestCase(lastTestCaseField.getText().replace("\\", "/"));
        settings.setLastTestingPath(lastTestingPathField.getText().replace("\\", "/"));
        settings.setTempProgramFileName(tempProgramFileField.getText());
        settings.setTempInputFileName(tempInputFileField.getText());
        settings.setTempOutputFileName(tempOutputFileField.getText());
        settings.setResultsFileName(resultsFileNameField.getText());
        settings.saveSettings();
        setVisible(false);
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void macDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macDefaultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_macDefaultsButtonActionPerformed

    private void linuxDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linuxDefaultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linuxDefaultsButtonActionPerformed
    
    /**
     * Runs python executor path validity test
     */
    private void pythonTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonTestButtonActionPerformed
        try{
            String message = PythonExecutor.runTestPath(pythonExecutableField.getText().replace("\\", "/"));
            messageLabel.setText(message);
        } catch (Exception IOException) {}
        
    }//GEN-LAST:event_pythonTestButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = pythonExecutableField.getText();
        JFileChooser chooser = new JFileChooser(path);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        File executable = chooser.getSelectedFile();
        path = executable.getPath().replace("\\","/");
        pythonExecutableField.setText( path );
//            
//            int lastSlash = path.lastIndexOf('/');
//            //Unsure of the necessity of the if-statement check...
//            //Shorter means: subPath = path.substring(0, path.lastIndexOf('\\'));
//                if (lastSlash > 0) {
//                    subPath = path.substring(0, lastSlash);
//                }
//                testCaseField.setText(path);
//                
//            // Only do the following if the test case path has changed
//            if( !testingPathField.getText().equals( subPath ) ) {
//                
//                //Sets text labels for the option dialog buttons
//                Object[] options = {"Yes", "No", "Change and Run"};
//                
//                //Adds and scales a file folder icon to replace the default icon
//                ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/File Folder Icon.png"));
//                Image image = icon.getImage(); 
//                Image newImage = image.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);  
//                icon = new ImageIcon(newImage);
//          
//                int sameFolder = JOptionPane.showOptionDialog(this,"Set testing path to same folder?",
//                        "Change Testing Path", JOptionPane.YES_NO_CANCEL_OPTION,
//                        JOptionPane.QUESTION_MESSAGE, icon, options, options[0]);
//           
//                if( sameFolder != JOptionPane.NO_OPTION) {
//                    testingPathField.setText(subPath);
//                    if( sameFolder == JOptionPane.CANCEL_OPTION ) {
//                        runTests();
//                    }
//                }
//            }
//        }











        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField idleExecutableField;
    private javax.swing.JLabel idleExecutableLabel;
    private javax.swing.JButton idleTestButton;
    private javax.swing.JLabel infoOnlyLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField lastTestCaseField;
    private javax.swing.JLabel lastTestCaseLabel;
    private javax.swing.JTextField lastTestingPathField;
    private javax.swing.JLabel lastTestingPathLabel;
    private javax.swing.JButton linuxDefaultsButton;
    private javax.swing.JButton macDefaultsButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel programFileNameLabel;
    private javax.swing.JTextField pythonExecutableField;
    private javax.swing.JLabel pythonExecutableLabel;
    private javax.swing.JButton pythonTestButton;
    private javax.swing.JTextField resultsFileNameField;
    private javax.swing.JLabel resultsFileNameLabel;
    private javax.swing.JTextField tempInputFileField;
    private javax.swing.JLabel tempInputFileLabel;
    private javax.swing.JTextField tempOutputFileField;
    private javax.swing.JLabel tempOutputFileLabel;
    private javax.swing.JTextField tempProgramFileField;
    private javax.swing.JButton winDefaultsButton;
    // End of variables declaration//GEN-END:variables
    private ProgramSettings settings;
}
